trigger:
  branches:
    include:
      - master
      - develop
  paths:
    include:
      - Minor.Miffy.Core/
      - Minor.Miffy.Core.Test/
      - Minor.Miffy.MicroServices/
      - Minor.Miffy.MicroServices.Test/
      - Minor.Miffy.MicroServices.Test.Conventions/
      - Minor.Miffy.Microservices.Test.Integration/
      - Minor.Miffy.RabbitMQBus/
      - Minor.Miffy.RabbitMQBus.Test/
      - Minor.Miffy.RabbitMQBus.Test.Integration/
      - azure-pipelines.yaml

variables:
  buildConfiguration: 'Release'
  projects: |
    Minor.Miffy.Core/Minor.Miffy.Core.csproj
    Minor.Miffy.Microservices/Minor.Miffy.Microservices.csproj
    Minor.Miffy.RabbitMQBus/Minor.Miffy.RabbitMQBus.csproj
  testProjects: |
    Minor.Miffy.Core.Test
    Minor.Miffy.MicroServices.Test
    Minor.Miffy.MicroServices.Test.Conventions
    Minor.Miffy.RabbitMQBus.Test
  integrationTestProjects: |
    Minor.Miffy.MicroServices.Test.Integration
    Minor.Miffy.RabbitMQBus.Test.Integration
  projectKey: MaartenH:Miffy
  projectName: MaartenH Miffy

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: SonarQubePrepare@4
            condition: eq(variables['build.sourcebranch'], 'refs/heads/master')
            inputs:
              SonarQube: 'SonarQube Service Connection'
              scannerMode: 'MSBuild'
              projectKey: $(projectKey)
              projectName: $(projectName)
              
          - task: DotNetCoreCLI@2
            displayName: 'dotnet build'
            inputs:
              projects: $(projects)
              arguments: '--configuration $(BuildConfiguration)'
        
          - task: DotNetCoreCLI@2
            displayName: 'dotnet test'
            inputs:
              command: test
              projects: $(testProjects)
              arguments: '--configuration $(BuildConfiguration) --collect:"Code Coverage"'

          - task: SonarQubeAnalyze@4
            condition: eq(variables['build.sourcebranch'], 'refs/heads/master')
          - task: SonarQubePublish@4
            condition: eq(variables['build.sourcebranch'], 'refs/heads/master')
            inputs:
              pollingTimeoutSec: '300'
          - task: sonar-buildbreaker@8
            condition: eq(variables['build.sourcebranch'], 'refs/heads/master')
            inputs:
              SonarQube: 'SonarQube Service Connection'
  - stage: Integration Tests
    displayName: Integration Tests
    dependsOn: Build
    jobs:
      - job: Integration Tests
        displayName: Integration Tests
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          # Not the cleanest way, but it works and it means I don't need a running server
          - bash: |
              docker pull --platform linux --experimental rabbitmq:3-alpine
              docker run -d -p 5672:5672 --name rabbitmq rabbitmq:3-alpine
            displayName: 'docker run rabbitmq'

          - task: DotNetCoreCLI@2
            displayName: 'dotnet test'
            inputs:
              command: test
              projects: $(integrationTestProjects)
              arguments: '--configuration $(BuildConfiguration)'
    
  - stage: Release
    displayName: Release
    dependsOn: Integration Tests
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - job: Release
        displayName: Release
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'dotnet build'
            inputs:
              projects: $(projects)
              arguments: '--configuration $(BuildConfiguration)'

          # To be sure ;-)
          - task: DotNetCoreCLI@2
            displayName: 'dotnet test'
            inputs:
              command: test
              projects: $(testProjects)
              arguments: '--configuration $(BuildConfiguration)'

          - task: DotNetCoreCLI@2
            displayName: 'dotnet pack'
            inputs:
              command: 'pack'
              packagesToPack: '**/*.csproj'
              patchVersion: $(Build.BuildId)
              nobuild: true

          - task: NuGetCommand@2
            displayName: 'nuget.org nuget push'
            inputs:
              command: 'push'
              packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
              nuGetFeedType: 'external'
              publishFeedCredentials: 'NuGet feed'