trigger:
  branches:
    include:
      - master

variables:
  buildConfiguration: 'Release'
  projects: |
    Minor.Miffy.Core/Minor.Miffy.Core.csproj
    Minor.Miffy.Microservices/Minor.Miffy.Microservices.csproj
    Minor.Miffy.RabbitMQBus/Minor.Miffy.RabbitMQBus.csproj
  testProjects: |
    Minor.Miffy.Core.Test
    Minor.Miffy.MicroServices.Test
    Minor.Miffy.MicroServices.Test.Conventions
    Minor.Miffy.RabbitMQBus.Test

stages:
  - stage: PreRelease
    displayName: PreRelease
    jobs:
      - job: PreRelease
        displayName: PreRelease
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'dotnet build'
            inputs:
              projects: $(projects)
              arguments: '--configuration $(BuildConfiguration)'
        
          - task: DotNetCoreCLI@2
            displayName: 'dotnet test'
            inputs:
              command: test
              projects: $(testProjects)
              arguments: '--configuration $(BuildConfiguration)'
        
          - task: DotNetCoreCLI@2
            displayName: 'dotnet pack'
            inputs:
              command: 'pack'
              packagesToPack: $(projects)
              versioningScheme: byPrereleaseNumber
              majorVersion: 1
              minorVersion: 0
              patchVersion: $(Build.BuildId)
              nobuild: true
        
          - task: DotNetCoreCLI@2
            displayName: 'nuget push'
            inputs:
              command: 'push'
              packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
              nuGetFeedType: 'internal'
              publishVstsFeed: 'd2d10d82-d2e1-4909-9810-5bf6d3a2eba4'
  - stage: Release
    displayName: Release
    jobs:
      - job: Release
        displayName: Release
        pool:
          vmImage: 'ubuntu-latest'
          steps:
            - task: DotNetCoreCLI@2
              displayName: 'dotnet build'
              inputs:
                projects: $(projects)
                arguments: '--configuration $(BuildConfiguration)'

            - task: DotNetCoreCLI@2
              displayName: 'dotnet test'
              inputs:
                command: test
                projects: $(testProjects)
                arguments: '--configuration $(BuildConfiguration)'

            - task: DotNetCoreCLI@2
              displayName: 'dotnet pack'
              inputs:
                command: 'pack'
                packagesToPack: $(projects)
                versioningScheme: byReleaseNumber
                majorVersion: 1
                minorVersion: 0
                patchVersion: $(Build.BuildId)
                nobuild: true

            - task: DotNetCoreCLI@2
              displayName: 'nuget push'
              inputs:
                command: 'push'
                packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
                nuGetFeedType: 'internal'
                publishVstsFeed: 'd2d10d82-d2e1-4909-9810-5bf6d3a2eba4'