trigger:
  branches:
    include:
      - master
      - develop
  paths:
    include:
      - Miffy.Core/
      - Miffy.Core.Test/
      - Miffy.MicroServices/
      - Miffy.MicroServices.Test/
      - Miffy.MicroServices.Test.Conventions/
      - Miffy.Microservices.Test.Integration/
      - Miffy.RabbitMQBus/
      - Miffy.RabbitMQBus.Test/
      - Miffy.RabbitMQBus.Test.Integration/
      - azure-pipelines.yaml

variables:
  buildConfiguration: 'Release'
  projects: |
    Miffy.Core/Miffy.Core.csproj
    Miffy.Microservices/Miffy.Microservices.csproj
    Miffy.RabbitMQBus/Miffy.RabbitMQBus.csproj
  testProjects: |
    Miffy.Core.Test
    Miffy.MicroServices.Test
    Miffy.MicroServices.Test.Conventions
    Miffy.RabbitMQBus.Test
  integrationTestProjects: |
    **/*.Integration/*.csproj
  projectKey: MaartenH:Miffy
  projectName: MaartenH Miffy

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'dotnet build'
            inputs:
              projects: $(projects)

          - task: DotNetCoreCLI@2
            displayName: 'dotnet test'
            inputs:
              command: test
              projects: $(testProjects)
              arguments: '--configuration $(BuildConfiguration) --collect:"Code Coverage"'

  - stage: Integration
    displayName: Integration Tests
    dependsOn: Build
    jobs:
      - job: Integration
        displayName: Integration Tests
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          # Not the cleanest way, but it works and it means I don't need a running server
          - bash: |
              docker run -d -p 5672:5672 --name rabbitmq rabbitmq:3-alpine
            displayName: 'docker run rabbitmq'

          - task: DotNetCoreCLI@2
            displayName: 'dotnet test'
            inputs:
              command: test
              projects: $(integrationTestProjects)
              arguments: '--configuration $(BuildConfiguration)'

  - stage: Release
    displayName: Release
    dependsOn: Integration
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - job: Release
        displayName: Release
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'dotnet pack'
            inputs:
              command: 'pack'
              packagesToPack: '**/*.csproj'
              patchVersion: $(Build.BuildId)

          - task: NuGetCommand@2
            displayName: 'nuget.org nuget push'
            inputs:
              allowPackageConflicts: true
              command: 'push'
              packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
              nuGetFeedType: 'external'
              publishFeedCredentials: 'NuGet feed'
