trigger:
  branches:
    include:
      - master
  paths:
    include:
      - Minor.Miffy.Core/*
      - Minor.Miffy.Microservices/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  projectPath: 'Minor.Miffy.Core'
  projectTestPath: 'Minor.Miffy.Core.Test'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      projects: '$(projectPath)/*.csproj'
      arguments: '--configuration $(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: test
      projects: '$(projectTestPath)/*.csproj'
      arguments: '--configuration $(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      packagesToPack: '$(projectPath)/*.csproj'
      nobuild: true
      versioningScheme: 'off'

  - task: 

  - task: DotNetCoreCLI@2
    inputs:
      majorVersion: 1
      minorVersion: 0
      patchVersion: 1
      #$(Build.BuildId)
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'd2d10d82-d2e1-4909-9810-5bf6d3a2eba4'

