trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  abstractionsProjectPath: Minor.Miffy.Core.Test
  abstractionsTestProjectPath: Minor.Miffy.Core.Test
  microservicesProjectPath: Minor.Miffy.Microservices
  microservicesTestProjectPath: Minor.Miffy.MicroServices.Test
  microservicesTestConventionsProjectPath: Minor.Miffy.MicroServices.Test.Conventions
  rabbitMQTestProjectPath: Minor.Miffy.RabbitMQBus.Test

steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      projects: '**/*.csproj'
      arguments: '--configuration $(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: test
      projects: '*Test/*.csrproj'
      arguments: '--configuration $(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj'
      nobuild: true
      versioningScheme: 'off'

  - task: DotNetCoreCLI@2
    inputs:
      majorVersion: 1
      minorVersion: 0
      patchVersion: $(Build.BuildId)
      command: 'pack'
      packagesToPack: '**/*.csproj'
      nobuild: true
      versioningScheme: 'off'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'd2d10d82-d2e1-4909-9810-5bf6d3a2eba4'
